### ISSUE TITLE
Suggestion: For the Autosuggest box, have tab accept the suggestion, as it is the industry standard.

### ISSUE THREAD

**Issue by AlexanderBlackman** [AndrewKeepCoding/AK.Toolkit#10]
Visual Studio and Gmail use 'tab' to accept a suggestion, so people won't be used to clicking 'right arrow'

**Comment by AndrewKeepCoding** [comment]
Hi @AlexanderBlackman! Thanks for the feed back! I totally agree with you.
I think these are what happens when 'tab' is pressed.

- Accept the suggestion if any
- Go to the next control if there is no suggestion

Let me know if you have other thing in mind.
(I'm currently working on another feature for this **AK.Toolkit**, so I won't be able to work on your suggestion for a week maybe?)

**Comment by AndrewKeepCoding** [comment]
@AlexanderBlackman Sorry this took this long.
